### ISSUE TITLE
Can't use version function

### ISSUE THREAD

**Issue by a-komarev** [DraperStudio/Laravel-Elixir-Packer#2]
When packer is active - version function not executing.

```json
mix.packer('resources/assets/js/all.js', 'public/assets/js/all.js');

mix.version([
    'public/assets/js/all.js'
]);
```

If comment out packer and just copy resource in public folder - version files will be created.

**Comment by DraperStudio** [comment]
Just tried the following and it worked fine.

```js
var elixir = require('laravel-elixir');

require('laravel-elixir-packer');

elixir(function(mix) {
    mix.packer('public/app.js', 'public/app.pkgd.js');

    mix.version(['public/app.pkgd.js']);
});
```

Does the `public/assets/js/all.js` file exist?

**Comment by a-komarev** [comment]
Yes... and packer creating a new file from it.

**Comment by DraperStudio** [comment]
What is the error message you get? Maybe there is a permission issue.

Just the info that it isn't working isn't much of a help to me since I tested with multiple files and it worked everytime.

**Comment by a-komarev** [comment]
There is no errors. Is there any way to run gulp with extended debugging output?

**Comment by a-komarev** [comment]
>[11:51:06] Finished 'scripts' after 27 ms
>[11:51:06] Starting 'packer'...

And after that gulp just stopping. Just saw that phpUnit isn't executing too.

```json
"name": "laravel-elixir",
"version": "3.1.0",
```

**Comment by DraperStudio** [comment]
Run the following any try it again, sometimes it is a permission issue.

`sudo chown -R `whoami` node_modules`
`sudo chown -R `whoami` public`

Also make sure you don't have any syntax errors in your javascript or packer will most likely crash.

**Comment by a-komarev** [comment]
Rechecked, permissions are ok.

in `laravel-elixir-packer/index.js` function `!filendir.ws(dest, packedContents)` is creating file and putting content in it, but all other tasks are interrupting in case if `return` of your script.

The only difference I saw in your package and another ones, that you are returning notification, and `laravel-elixir/tasks/copy.js` for example returning:
```js
return (
    gulp
    .src(paths.src.path)
    .pipe($.if(! paths.output.isDir, $.rename(paths.output.name)))
    .pipe(gulp.dest(paths.output.baseDir))
);
```

**Comment by DraperStudio** [comment]
Changed a few things so you can try `"laravel-elixir-packer": "^1.2.0"`.

````
[11:39:33] Using gulpfile ~/Sites/elixir-test/gulpfile.js
[11:39:33] Starting 'default'...
[11:39:33] Starting 'packer'...
[11:39:33] Finished 'default' after 14 ms
[11:39:33] Finished 'packer' after 32 ms
[11:39:33] Starting 'version'...

Fetching Version Source Files...
   - public/build/app.min.js


Saving To...
   - public/build

[11:39:33] Finished 'version' after 31 ms
```

**Comment by a-komarev** [comment]
Thanks! Now it works. Noticed that behavior has been changed.

1. Now packer accepting destination directory as second parameter (was file before)
2. Packer now renaming output file by automatically adding .min before file extension

My script now looks like:

```js
mix.packer('public/assets/js/all.js', 'public/assets/js/pkgd');

mix.version([
    'public/assets/js/pkgd/all.min.js'
]);
```
