### ISSUE TITLE
Packer breaking script

### ISSUE THREAD

**Issue by a-komarev** [DraperStudio/Laravel-Elixir-Packer#4]
Sorry for spamming issues :}

When `gulp` command is executing - packed script is breaking.
```
Firefox console:
SyntaxError: missing ; before statement

Chrome console:
Uncaught SyntaxError: Unexpected token if
```

When `gulp --production` is executed - everything working fine.

I've tried to turn off all options but that not helped:
```js
base62Encode: false,
shrinkVariables: false
```

Do you have any ideas what could it be?

**Comment by DraperStudio** [comment]
Most likely a syntax error in your script. Missing a semicolon after something or a leading semicolon.

Next time please create a fork, find the issue and send a PR instead of spamming issues for everthing.
